# Array Manipulation

### Changing Shape

In [1]:
import numpy as np


In [2]:
a = np.arange(8)


# Reshape splits into 2 rows of 4 columns.
# Can't reshape if the dimensions aren't equal between
# Original and target. e.g. array of 8 elements, is same as 2 x 4 element matrix
b = a.reshape(2,4)

In [3]:
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
# Can also flatten a matrix back to an array

b.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
# Can also modify the ordering to do C/R ordering
# The "F" stands for FORTRAN
b.flatten(order="F")

array([0, 4, 1, 5, 2, 6, 3, 7])

#### Transpose

In [6]:
a = np.arange(12).reshape((4,3))

In [7]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
# NOTE how the whole matrix has been transposed
# Creates rows out of columns, cols out of rows
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

#### Change To Tensor

In [9]:
b = np.arange(12)

In [10]:
# This adds a THIRD dimension to make it a tensor
b = b.reshape(2,3,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

#### Flexible change of axis. Take any dimension and reorder it

In [11]:
# In the below example. We're taking the 
# Highest ordered axis and swapping the 1st index with the 2nd index
# e.g. if we had a 3d array, and wanted to
# access the 3rd matrix's 4th row's 2nd item, we'd 
# use this >>> my_array[2][3][1]

np.moveaxis(b,0,1)

array([[[ 0,  1],
        [ 6,  7]],

       [[ 2,  3],
        [ 8,  9]],

       [[ 4,  5],
        [10, 11]]])

In [12]:
# The above is saying "move the currently first index ...
# forward one. Which makes everything on the 2nd index, now
# the 1st index"

# In this case, all the rows become columns and columns become rows

### Arithmetic Operations

In [13]:
z = np.arange(9).reshape(3,3)

In [14]:
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
b = np.array(([10,11,12]))
np.add(z,b)

array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20]])

In [16]:
np.subtract(b,z)

array([[10, 10, 10],
       [ 7,  7,  7],
       [ 4,  4,  4]])

In [17]:
np.multiply(z,b)

array([[ 0, 11, 24],
       [30, 44, 60],
       [60, 77, 96]])

### Slicing Array

In [18]:

a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
# Same as python
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
# Can also pass a slice function to the index of an array
# This is "start at 2, stop when value <= 10, increment by 3"
ss = slice(0,10,3)
a[ss]

array([0, 3, 6, 9])

### Iterating over an array

In [21]:
q = np.arange(0,45,5)
q = q.reshape((3,3))
q

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [22]:
for x in np.nditer(q):
    print(x)

0
5
10
15
20
25
30
35
40


### Concatenate Arrays (on different axis)

In [23]:
a = np.arange(12).reshape(3,4)
b = np.arange(13,25).reshape(3,4)

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [26]:
# Concatenated on Index 0 ... therefore, adds all the rows from array
# B to array A
np.concatenate((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [27]:
# Now concatenated on Index 1 ... therefore, concatenates at the row level
# for all the arrays being joined. i.e. all the rows at index 0, all of their elements
# get joined together ... and so on.
np.concatenate((a, b), axis=1)

array([[ 0,  1,  2,  3, 13, 14, 15, 16],
       [ 4,  5,  6,  7, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 21, 22, 23, 24]])

#### Stacking arrays together

In [30]:
# Concatenate arrays by stacking rows of component arrays (for 2D arrays that is)
np.vstack((a,b))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [31]:
# Append the elments of the matching row index from each constituent array into
# a single array

np.hstack((a,b))

array([[ 0,  1,  2,  3, 13, 14, 15, 16],
       [ 4,  5,  6,  7, 17, 18, 19, 20],
       [ 8,  9, 10, 11, 21, 22, 23, 24]])

### Split Array

In [ ]:
zz = np.arange(12)
# Split zz into 3 separate and equal arrays
np.split(zz, 3)

### Resize an array

In [ ]:
print(b.shape)
# Makes the array larger, but fills the 
# As was o
np.resize(b, (2,10))

### Histograms

In [ ]:
from matplotlib import pyplot as plt


a = np.random.randint(0,100,30)

In [ ]:
a

In [ ]:
plt.hist(a, bins=[20,40,60,80])

In [ ]:
fig, ax = plt.subplots()
ax.set_title("Hiya")
ax.plot(a)

In [ ]:
import random
x = np.random.randint(0,100,100)
y = np.random.randint(0,100,100)
scalars = np.random.randint(0,100,100)

plt.scatter(x,y,scalars)

### Useful Functions

In [ ]:
# Returns an array of evenly spaced values between start_value and end_value
# with a specified number of elements
# e.g. 0,100,40 --> give me an array of elements starting with 0 and ending with 100
# that has 40 elements
a = np.linspace(0,100,60)

In [ ]:
a

In [ ]:
# Sum of all elements in the array.
# Interestingly, the sum in relation to the linspace function
# sum = (end_value * num_elements) / 2
np.sum(a)

In [ ]:
a = np.reshape(a,(10,3,2))
a

In [ ]:
z = np.sum(a, axis=2)
z

In [ ]:
np.std(a)

In [ ]:
np.average(a)

In [ ]:
yy = np.zeros((6,6), dtype=int)

# Can use the slice operator to manipulate different indexes
# This says "starting at row index 1 and then every second row after that"
# In each of those rows, for every 2nd element, set that element to 1
yy[1::2,::2] = 1

In [ ]:
yy

In [ ]:
yy[::2,1::2] = 1

In [ ]:
yy

### Create a random matrix

In [ ]:
# NOTE: ALL THE RANDOM FUNCTIONS CAN BE FOUND HERE....
# https://numpy.org/doc/stable/reference/random/generator.html



# Array of random integers from 0 --> 10
rr = np.random.randint(10, size=(10,10))

In [ ]:
rr

In [ ]:
np.random.standard_normal(10)

In [ ]:
# Generate a standard normal distribution of values
nnn = np.random.standard_normal(100000)

In [ ]:
plt.hist(nnn)

In [ ]:
l = np.random.power(30, 10000)

In [ ]:
l

In [ ]:
fix, axz = plt.subplots()
axz.hist(l)

In [ ]:
np.argwhere(rr==9)

### Sinewave

In [ ]:
# For the duration of 3pi, return the result of the sin function
x = np.arange(0, 3*np.pi,0.1)
# Remember, sin is the ratio of opposite/hypo for a given angle
y = np.sin(x)

plt.plot(x,y)
plt.show()