In [2]:
import numpy as np


#Numpy array is fast and uses less memory

#a = np.array(range(0,1000))

In [3]:
import time
import sys

b = range(1000)
#Show memory footprint of a regular python list
print("Python list memory footprint --> " + str(sys.getsizeof(6) * len(b)))

c = np.arange(1000)
#Show memory footprint of a numpy array
print("Numpy memory footprint --> " + str(c.size * c.itemsize))

Python list memory footprint --> 28000
Numpy memory footprint --> 8000


In [4]:
size = 1000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x+y) for x,y in zip(l1, l2)]
print("Python List Took {}".format(time.time() - start))

start_2 = time.time()

# THIS is freaking AWESOME!
# Numpy knows these two are arrays so does matrix addition
result = a1 + a2
print("Numpy Took {}".format(time.time() - start_2))

Python List Took 0.0700688362121582
Numpy Took 0.014641523361206055


In [5]:

z = np.array([[1000,2], [3,4], [5,6]])
print(z)

[[1000    2]
 [   3    4]
 [   5    6]]


In [6]:
#How many dimensions?
print("The number of dimensions (aka columns) each row has = %s " % str(z.ndim))

#What is the "shape" of the array in R:C format
print("This array has {} rows and {} columns".format(z.shape[0], z.shape[1]))

The number of dimensions (aka columns) each row has = 2 
This array has 3 rows and 2 columns


In [7]:
#How big in BYTEs each array element is....
print(z.itemsize)

8


In [8]:
# Convert all values to another type by passing the dtype arg
z = np.array([[1000,2], [3,4], [5,6]], dtype=np.float64)
print(z)
print(z.itemsize)

[[1000.    2.]
 [   3.    4.]
 [   5.    6.]]
8


In [9]:
z.shape

(3, 2)

In [10]:
# Creates an array of R/C shape 3,4 filled with zeroes of type float
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
z

array([[1000.,    2.],
       [   3.,    4.],
       [   5.,    6.]])

In [13]:
y = np.array(([20,30],[40,50],[60,70]), dtype=np.float64)

# Boom ... matrix-matrix addition
z + y

array([[1020.,   32.],
       [  43.,   54.],
       [  65.,   76.]])